### ISSUE TITLE
Creating RS project xml

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/inundation#8]
From @kbartelt email:

>   I am trying to write code to automate the creation of the project.rs.xml file for my inundation projects. I recorded a [brief video here](https://youtu.be/pTUv5LGu8xM) with my limited understanding of how to start and to see if I'm using the correct BRAT scripts as templates for generating the xml. It would be great if you had time to verify whether I'm using the correct code from the pyBRAT Repo ([BRATProject.py](https://github.com/Riverscapes/pyBRAT/blob/master/BRATProject.py) & [BRAT_Table.py](https://github.com/Riverscapes/pyBRAT/blob/master/BRAT_table.py)) and/or could set up a call to go over some of this. 
> 
> Joe, I added you to this email because you mentioned also wanting to figure out how to generate the project xml.
> 
> Thank you,
> 
> Karen

**Comment by philipbaileynar** [comment]
@kbartelt I think you're looking at the wrong code.

You want to look at the code in the [sqlBRAT repo](https://github.com/Riverscapes/sqlBRAT). This [video](https://youtu.be/sD2w-m1IF5w) should help you get started. Take a look and perhaps make a first attempt. Then ping me should you want to still proceed with an online meeting to discuss or walk through the process.

**Comment by kbartelt** [comment]
Thanks for the video @philipbaileynar. I think I will probably need to have a call at some point to go over some things but I have a couple questions as I make a first attempt.

So here is the create_project function directly copied from the sqlBRAT repo that is the main method creating the xml

```
def create_project(huc, output_dir):

    project_name = 'Riverscapes Context for HUC {}'.format(huc)
    project = RSProject(cfg, output_dir)
    project.create(project_name, 'RSContext')

    project.add_project_meta({
        'HUC{}'.format(len(huc)): str(huc)
    })

    realizations = project.XMLBuilder.add_sub_element(project.XMLBuilder.root, 'Realizations')
    realization = project.XMLBuilder.add_sub_element(realizations, 'RSContext', None, {
        'id': 'RSContext1',
        'dateCreated': datetime.datetime.now().isoformat(),
        'guid': str(uuid.uuid1()),
        'productVersion': cfg.version
    })
    project.XMLBuilder.add_sub_element(realization, 'Name', project_name)

    project.XMLBuilder.write()
    return project, realization
```

I want to see if I am correctly understanding how I should use this function. I want to have xml nodes called Inputs and Realizations with children nodes to Realizations called RS_Context and DCE. I pasted an example below

```
<Project
    <Name>site_name</Name>
    <ProjectType>RIM</ProjectType>
    <MetaData>
	<Meta name="HUC8">16010203</Meta>
    <Inputs></Inputs>
    <Realizations>
        <RS_Context id='RS_01'></RS_Context>
        <DCE id='DCE_01'>
            <Name>image_date</Name>
        </DCE>
    </Realizations>
</Project>
```

Do I then add the Inputs and Realization (and RS_Context and DCE) nodes within the actual definition of the create_project function? something like what is shown below? or should the rs_context and dce nodes be added outside of this function after the project is already created?

```
def create_project(huc, output_dir, site_name, image_date):

    project_name = site_name
    project = RSProject(cfg, output_dir)
    project.create(project_name, 'RIM')

    project.add_project_meta({
        'HUC{}'.format(len(huc)): str(huc),
    })

    inputs = project.XMLBuilder.add_sub_element(project.XMLBuilder.root, 'Inputs')
    realizations = project.XMLBuilder.add_sub_element(project.XMLBuilder.root, 'Realizations')
    rs_context = project.XMLBuilder.add_sub_element(realizations, 'RS_Context', None, {
        'id': 'RS_01',
    })
    dce = project.XMLBuilder.add_sub_element(realizations, 'DCE', None, {
        'id': 'DCE_01',
    })
    project.XMLBuilder.add_sub_element(dce, 'Name', image_date)

    project.XMLBuilder.write()
    return project, inputs, rs_context, dce
```
and then it looks like all actual files that fit into either Inputs or Realizations are added to the xml with the add_project_vector or add_project_raster functions, which I think I am understanding.

How do I later update the xml from a different script after the project file has already been initially created?

**Comment by philipbaileynar** [comment]
@kbartelt I'm out this week. Ping me after 25 July to set up a call. Happy to help. If it's urgent you can contact @MattReimer. He knows this stuff even better than me.

**Comment by kbartelt** [comment]
@philipbaileynar do you have time this week to set up a call to go over this? 

Currently I'm having  issues with my python environment or version and am unable to install gdal and other packages used in the supporting scripts and haven't been able to test whether any of the code i'm trying is working. Do you have a specific python version you recommend using?

**Comment by philipbaileynar** [comment]
@MattReimer can you help Karen please. Sounds like an online meeting need. Happy to provide background Matt if you want.

**Comment by MattReimer** [comment]
Sure. @kbartelt we can set something up tomorrow if you'd like. Let me know your availability.

**Comment by kbartelt** [comment]
That would be great, thank you. My availability tomorrow is open anytime after 11am MST.

**Comment by MattReimer** [comment]
How's 2pm MST?

I see your email isn't listed in the profile. You should be able to see my email listed on my github profile page. 
https://github.com/Mattreimer
Could you send me an email so I can set up the meeting?

**Comment by MattReimer** [comment]
I'm going to call this issue done for now. Please open a new one if there are further issues with the project xml creation
